"""empty message

Revision ID: 2354222a3da4
Revises: 
Create Date: 2019-03-28 17:29:52.132293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2354222a3da4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_member_bind', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_member_bind', sa.Column('test', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
