"""empty message

Revision ID: 284d72932a9d
Revises: 
Create Date: 2019-04-08 01:06:12.250237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284d72932a9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('light_spu_category',
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('spu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['light_other_category.id'], ),
    sa.ForeignKeyConstraint(['spu_id'], ['light_spu.id'], ),
    sa.PrimaryKeyConstraint('id', 'category_id', 'spu_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('light_spu_category')
    # ### end Alembic commands ###
