"""empty message

Revision ID: 2edba2bee684
Revises: bdccf264ddd3
Create Date: 2019-04-24 15:52:36.736372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edba2bee684'
down_revision = 'bdccf264ddd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_order', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('pay_order', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('pay_order', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pay_order', 'update_time')
    op.drop_column('pay_order', 'status')
    op.drop_column('pay_order', 'create_time')
    # ### end Alembic commands ###
