"""empty message

Revision ID: 2ef248ba274b
Revises: 2354222a3da4
Create Date: 2019-03-28 17:50:34.415636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ef248ba274b'
down_revision = '2354222a3da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_member_bind', 'extra',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('oauth_member_bind', 'unionid',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('oauth_member_bind', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('oauth_member_bind', 'updated_time')
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=24),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=24),
               nullable=False)
    op.add_column('oauth_member_bind', sa.Column('updated_time', mysql.DATETIME(), nullable=False))
    op.alter_column('oauth_member_bind', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('oauth_member_bind', 'unionid',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('oauth_member_bind', 'extra',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
