"""empty message

Revision ID: 31de86b849cc
Revises: 
Create Date: 2019-04-28 15:23:42.833187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31de86b849cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('light_category', sa.Column('is_leaf', sa.Boolean(), nullable=True))
    op.add_column('light_category', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('light_category', sa.Column('par_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'light_category', 'light_category', ['par_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'light_category', type_='foreignkey')
    op.drop_column('light_category', 'par_id')
    op.drop_column('light_category', 'level')
    op.drop_column('light_category', 'is_leaf')
    # ### end Alembic commands ###
