"""empty message

Revision ID: 74dd0d71a280
Revises: 02eaba6b6fe9
Create Date: 2019-05-06 16:18:02.587030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74dd0d71a280'
down_revision = '02eaba6b6fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pay_order', 'comment_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('pay_order', 'express_info',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=100),
               nullable=True)
    op.alter_column('pay_order', 'express_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('pay_order', 'note',
               existing_type=mysql.TEXT(collation='utf8mb4_bin'),
               nullable=True)
    op.alter_column('pay_order', 'pay_sn',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=128),
               nullable=True)
    op.alter_column('pay_order', 'pay_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('pay_order', 'prepay_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=128),
               nullable=True)
    op.alter_column('pay_order', 'yun_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pay_order', 'yun_price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('pay_order', 'prepay_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=128),
               nullable=False)
    op.alter_column('pay_order', 'pay_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('pay_order', 'pay_sn',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=128),
               nullable=False)
    op.alter_column('pay_order', 'note',
               existing_type=mysql.TEXT(collation='utf8mb4_bin'),
               nullable=False)
    op.alter_column('pay_order', 'express_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('pay_order', 'express_info',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=100),
               nullable=False)
    op.alter_column('pay_order', 'comment_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
