"""empty message

Revision ID: 8a01701e599d
Revises: a42a13a01afe
Create Date: 2019-02-26 11:47:27.581643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a01701e599d'
down_revision = 'a42a13a01afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('extra', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'extra')
    # ### end Alembic commands ###
