"""empty message

Revision ID: cb4011f1dca7
Revises: 2ef248ba274b
Create Date: 2019-03-28 18:53:52.605912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb4011f1dca7'
down_revision = '2ef248ba274b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_member_bind', 'client_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.add_column('user', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.drop_index('nickname', table_name='user')
    op.drop_index('phone', table_name='user')
    op.drop_column('user', 'avater')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avater', mysql.VARCHAR(length=200), nullable=True))
    op.create_index('phone', 'user', ['phone'], unique=True)
    op.create_index('nickname', 'user', ['nickname'], unique=True)
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_column('user', 'avatar')
    op.alter_column('oauth_member_bind', 'client_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
