"""empty message

Revision ID: cbc424851d93
Revises: f1b62423078a
Create Date: 2019-04-08 01:31:40.943415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbc424851d93'
down_revision = 'f1b62423078a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('light_spu_category', 'create_time')
    op.drop_column('light_spu_category', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('light_spu_category', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('light_spu_category', sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
