"""empty message

Revision ID: cc063926bd02
Revises: e16b9c12aa35
Create Date: 2019-04-23 10:48:17.617249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc063926bd02'
down_revision = 'e16b9c12aa35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('light_spu', sa.Column('auto_qr', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('light_spu', 'auto_qr')
    # ### end Alembic commands ###
