"""empty message

Revision ID: de65e567678c
Revises: cc063926bd02
Create Date: 2019-04-23 15:37:13.433008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de65e567678c'
down_revision = 'cc063926bd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gift')
    op.drop_index('isbn', table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('binding', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('publisher', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('pages', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pubdate', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('isbn', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('summary', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('extra', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('isbn', 'book', ['isbn'], unique=True)
    op.create_table('gift',
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('isbn', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('launched', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], name='gift_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
