"""empty message

Revision ID: e16b9c12aa35
Revises: fee30823a35d
Create Date: 2019-04-23 10:22:40.915110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16b9c12aa35'
down_revision = 'fee30823a35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('gift', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('light_category', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('light_other_category', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('light_sku', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('light_sku_spec', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('light_spec', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('light_spec_value', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('light_spu', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('light_spu_qrcode', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('light_spu_statement', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('oauth_member_bind', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_time')
    op.drop_column('oauth_member_bind', 'update_time')
    op.drop_column('light_spu_statement', 'update_time')
    op.drop_column('light_spu_qrcode', 'update_time')
    op.drop_column('light_spu', 'update_time')
    op.drop_column('light_spec_value', 'update_time')
    op.drop_column('light_spec', 'update_time')
    op.drop_column('light_sku_spec', 'update_time')
    op.drop_column('light_sku', 'update_time')
    op.drop_column('light_other_category', 'update_time')
    op.drop_column('light_category', 'update_time')
    op.drop_column('gift', 'update_time')
    op.drop_column('book', 'update_time')
    # ### end Alembic commands ###
