"""empty message

Revision ID: f1b62423078a
Revises: 284d72932a9d
Create Date: 2019-04-08 01:17:12.205460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1b62423078a'
down_revision = '284d72932a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('light_spu_category', sa.Column('other_category_id', sa.Integer(), nullable=False))
    op.drop_constraint('light_spu_category_ibfk_1', 'light_spu_category', type_='foreignkey')
    op.create_foreign_key(None, 'light_spu_category', 'light_other_category', ['other_category_id'], ['id'])
    op.drop_column('light_spu_category', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('light_spu_category', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'light_spu_category', type_='foreignkey')
    op.create_foreign_key('light_spu_category_ibfk_1', 'light_spu_category', 'light_other_category', ['category_id'], ['id'])
    op.drop_column('light_spu_category', 'other_category_id')
    # ### end Alembic commands ###
